# Generated by Django 2.1.4 on 2018-12-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_info',
            name='commodity_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_info',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
