# Generated by Django 2.1.4 on 2018-12-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0003_auto_20181227_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_info',
            name='purchase_status',
            field=models.CharField(choices=[('finished', 'finished'), ('unfinished', 'unfinished'), ('error', 'error')], max_length=10),
        ),
    ]
