# Generated by Django 2.1.4 on 2018-12-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0004_auto_20181227_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_id', models.CharField(max_length=50)),
                ('commodity_name', models.CharField(max_length=100)),
                ('commodity_specification', models.CharField(max_length=100)),
                ('commodity_num', models.IntegerField()),
                ('commodity_price', models.FloatField()),
            ],
        ),
    ]
