# Generated by Django 2.1.4 on 2019-01-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0005_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('lack', 'lack'), ('rich', 'rich')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='status_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
