# Generated by Django 2.1.4 on 2019-01-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0008_auto_20190103_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='status',
        ),
    ]
