# Generated by Django 2.1.4 on 2019-01-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0009_remove_goods_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_tea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tea_sugar', models.CharField(choices=[('free', 'free'), ('normal', 'normal'), ('full', 'full')], max_length=10)),
                ('tea_temperature', models.CharField(choices=[('cold', 'cold'), ('normal', 'normal'), ('hot', 'hot')], max_length=10)),
                ('tea_additional', models.CharField(max_length=50)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tea_info',
            name='tea_additional',
        ),
        migrations.RemoveField(
            model_name='tea_info',
            name='tea_sugar',
        ),
        migrations.RemoveField(
            model_name='tea_info',
            name='tea_temperature',
        ),
        migrations.AddField(
            model_name='sale_tea',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamanagement.Tea_info'),
        ),
    ]
