# Generated by Django 2.1.4 on 2019-01-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0011_sale_tea_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea_addition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sale_tea',
            name='total_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
