# Generated by Django 2.1.4 on 2019-01-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0012_auto_20190105_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea_addition',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teamanagement.Goods'),
            preserve_default=False,
        ),
    ]
