# Generated by Django 2.1.4 on 2019-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0015_remove_sale_tea_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_info',
            name='discount_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale_info',
            name='original_price',
            field=models.FloatField(),
        ),
    ]
