# Generated by Django 2.1.4 on 2019-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0016_auto_20190107_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_info',
            name='staff_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
