# Generated by Django 2.1.4 on 2019-01-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0018_sale_tea_tea_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('purchase', 'purchase'), ('sales', 'sales')], max_length=10)),
                ('option_id', models.IntegerField()),
            ],
        ),
    ]
