# Generated by Django 2.1.4 on 2019-01-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamanagement', '0019_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_inout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('purchase', 'purchase'), ('sales', 'sales')], max_length=10)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamanagement.Goods')),
            ],
        ),
    ]
